name: Spotless Check

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different operating system if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Grant execute permissions to gradlew
      run: chmod +x ./gradlew  # This grants execute permissions to the gradlew script
  

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Set the Java version required for your project
        distribution: 'adopt' # Set the distribution type (e.g., 'jdk', 'temurin')

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'  # Set the Node.js version to 16.x

    - name: Build with Gradle
      run: ./gradlew :app:spotlessApply
